name: Build and Publish jupyterlite page to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build repo2jupyterlite
        uses: yuvipanda/repo2jupyterlite-action@main
      - name: Upload generated site
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

  publish:
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.publish.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Publish to GitHub Pages
        id: publish
        uses: actions/deploy-pages@v1
